# Generated by Django 3.2.22 on 2023-12-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0009_auto_20231114_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('', 'Selecciona el tipo de usuario'), ('Administrador', 'Administrador'), ('Alumno', 'Alumno')], default='', max_length=50, verbose_name='Tipo de Usuario'),
        ),
    ]
