# Generated by Django 3.2.22 on 2023-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0009_auto_20231114_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('', 'Selecciona el tipo de usuario'), ('Editor_contenido', 'Editor de contenido'), ('Revisor', 'Revisor'), ('Estudiante', 'Estudiante'), ('Visualizador', 'Visualizador'), ('Reporteria', 'Reporteria'), ('Administrador_empresa', 'Administrador empresa')], default='', max_length=50, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado_cuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
