# Generated by Django 3.2.22 on 2023-11-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CursosApp', '0003_auto_20231030_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_answer', models.CharField(max_length=255, null=True)),
                ('option_answer', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('option', 'Opción múltiple'), ('text', 'Texto')], max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255, null=True)),
                ('option_b', models.CharField(max_length=255, null=True)),
                ('option_c', models.CharField(max_length=255, null=True)),
                ('option_d', models.CharField(max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones_respuesta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='preguntas',
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='OpcionRespuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Quizz',
        ),
        migrations.AddField(
            model_name='questioncontent',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CursosApp.quizcontent'),
        ),
        migrations.AddField(
            model_name='answercontent',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.questioncontent'),
        ),
        migrations.AddField(
            model_name='answercontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
