# Generated by Django 3.2.22 on 2023-11-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0004_auto_20231109_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenidoContent',
        ),
    ]
