# Generated by Django 4.2.6 on 2023-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0005_delete_contenidocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
