# Generated by Django 4.2.6 on 2023-11-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0006_curso_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='estado',
            new_name='aprobado',
        ),
    ]
