# Generated by Django 4.2.6 on 2023-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0007_rename_estado_curso_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
