# Generated by Django 4.2.6 on 2023-11-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0008_curso_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='orden',
        ),
    ]
