# Generated by Django 4.2.6 on 2023-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0012_video_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontent',
            name='orden',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
