# Generated by Django 4.2.6 on 2023-11-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0013_alter_quizcontent_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncontent',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CursosApp.quizcontent'),
            preserve_default=False,
        ),
    ]
