# Generated by Django 4.2.6 on 2023-11-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0014_alter_questioncontent_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontent',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncontent',
            name='unidad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso'),
            preserve_default=False,
        ),
    ]
