# Generated by Django 3.2.22 on 2023-11-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0006_alter_curso_imagen'),
        ('CursosApp', '0018_alter_curso_nombre'),
    ]

    operations = [
    ]
