# Generated by Django 3.2.22 on 2023-11-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0020_alter_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadcurso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='unidades'),
        ),
    ]
