# Generated by Django 3.2.22 on 2023-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0021_unidadcurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadcurso',
            name='margen_izquierdo',
            field=models.IntegerField(default=0),
        ),
    ]
