# Generated by Django 3.2.22 on 2023-12-12 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CursosApp', '0022_unidadcurso_margen_izquierdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
            },
        ),
        migrations.CreateModel(
            name='QuizProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.progreso')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.quizcontent')),
            ],
            options={
                'unique_together': {('progreso', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='progreso',
            name='quizzes_completados',
            field=models.ManyToManyField(blank=True, through='CursosApp.QuizProgreso', to='CursosApp.QuizContent'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progreso',
            name='videos_vistos',
            field=models.ManyToManyField(blank=True, to='CursosApp.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('user', 'unidad')},
        ),
    ]
